config/routes.rb
Rails.application.routes.draw do
  root 'statuses#dashboard'
  resources :statuses
  get 'dashboard', to: 'statuses#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
  validates :date, presence: true
  has_one_attached :status_picture
  
  def total_hours_count
    tasks.sum(:hour)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  validates :task_name, presence: true, length: { minimum:5 }
  validates :git_pr_link, presence: true
  validates :hour, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def index
    @statuses = Status.paginate(page: params[:page], per_page: 2)
  end

  def show
    @status = Status.find(params[:id])
    @tasks = @status.tasks
  end

  def dashboard
  end

  def new
    @status = Status.new
    @tasks = @status.tasks.build
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      SendNotificationsJob.set(wait: 30.minutes).perform_later(@status)
      flash[:success] = 'Email has been sent successfully..'
      redirect_to @status
    else
      render 'new'
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])
    if params[:Preview]
      puts 'hello....'
    end
    if @status.update(status_params)
      flash[:success] = 'status has been updated successfully..'
      redirect_to status_path
    else
      render 'edit'
    end
  end

  def destroy
    @status = Status.find(params[:id])
    @status.destroy
    redirect_to statuses_path
  end

  private

  def status_params
    params.require(:status).permit(:date, :status_picture, tasks_attributes: [:id, :task_name, :git_pr_link, :hour, :_destroy ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="margin-top: 70%;">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6 m-auto text-center">
        <div class="copyright">
          <p>Made with <a href="https://www.creative-tim.com/product/argon-dashboard" target="_blank"> Dashboard</a> created by rails developer </p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_sidebar.html.erb
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand pt-0 text-primary" href="https://www.creative-tim.com/product/argon-dashboard" target="_blank">
           STATUS UPDATE
          </a>
          <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
              <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="ni ni-bell-55"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <img alt="Image placeholder" src="https://demos.creative-tim.com/argon-dashboard/assets/img/theme/team-4.jpg">
                  </span>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                <div class=" dropdown-header noti-title">
                  <h6 class="text-overflow m-0">Welcome!</h6>
                </div>
                <a href="./examples/profile.html" class="dropdown-item">
                  <i class="ni ni-single-02"></i>
                  <span>My profile</span>
                </a>
                <a href="./examples/profile.html" class="dropdown-item">
                  <i class="ni ni-settings-gear-65"></i>
                  <span>Settings</span>
                </a>
                <a href="./examples/profile.html" class="dropdown-item">
                  <i class="ni ni-calendar-grid-58"></i>
                  <span>Activity</span>
                </a>
                <a href="./examples/profile.html" class="dropdown-item">
                  <i class="ni ni-support-16"></i>
                  <span>Support</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#!" class="dropdown-item">
                  <i class="ni ni-user-run"></i>
                  <span>Logout</span>
                </a>
              </div>
            </li>
          </ul>
          <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <div class="navbar-collapse-header d-md-none">
              <div class="row">
                <div class="col-6 collapse-brand">
                  <a href="javascript:void(0)">
                    Creative Tim
                  </a>
                </div>
                <div class="col-6 collapse-close">
                  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                    <span></span>
                    <span></span>
                  </button>
                </div>
              </div>
            </div>
            <form class="mt-4 mb-3 d-md-none">
              <div class="input-group input-group-rounded input-group-merge">
                <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    <span class="fa fa-search"></span>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to new_status_path, class: "nav-link"  do%>
                  <i class="fa fa-plus text-primary"></i>New status
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to statuses_path, class: "nav-link"  do%>
                  <i class="fa fa-history text-primary"></i>History
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="main-content">
        <!-- Top navbar -->
        <nav class="navbar navbar-tp navbar-expand-md navbar-dark bg-primary" id="navbar-main">
          <div class="container-fluid">
            <!-- Brand -->
            <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="./index.html">Dashboard</a>
            <!-- Form -->
            <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
              <div class="form-group mb-0">
                <div class="input-group input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                  </div>
                  <input class="form-control" placeholder="Search" type="text">
                </div>
              </div>
            </form>
            <!-- User -->
            <ul class="navbar-nav align-items-center d-none d-md-flex">
              <li class="nav-item dropdown">
                <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="media align-items-center">
                    <span class="avatar avatar-sm rounded-circle">
                      <img alt="Image placeholder" src="https://demos.creative-tim.com/argon-dashboard/assets/img/theme/team-4.jpg">
                    </span>
                    <div class="media-body ml-2 d-none d-lg-block">
                      <span class="mb-0 text-sm  font-weight-bold">Username</span>
                    </div>
                  </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                  <div class=" dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome!</h6>
                  </div>
                  <a href="./examples/profile.html" class="dropdown-item">
                    <i class="ni ni-single-02"></i>
                    <span>My profile</span>
                  </a>
                  <a href="./examples/profile.html" class="dropdown-item">
                    <i class="ni ni-settings-gear-65"></i>
                    <span>Settings</span>
                  </a>
                  <a href="./examples/profile.html" class="dropdown-item">
                    <i class="ni ni-calendar-grid-58"></i>
                    <span>Activity</span>
                  </a>
                  <a href="./examples/profile.html" class="dropdown-item">
                    <i class="ni ni-support-16"></i>
                    <span>Support</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#!" class="dropdown-item">
                    <i class="ni ni-user-run"></i>
                    <span>Logout</span>
                  </a>
                </div>
              </li>
            </ul>
          </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StatusUpdate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/sidebar' %>
    <%= render 'statuses/messages'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @status.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= @status.class.name.downcase %> from being saved</h4>
      <ul>
         <% @status.errors.full_messages.each do |message|%>
           <li><%= message %></li>
         <%end%>
      </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/statuses/_form.html.erb
<% if @status.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">
      The following errors prevented the <%= @status.class.name.downcase %> from being saved
    </h4>
    <ul>
      <% @status.errors.full_messages.each do |message|%>
        <li class="text-start"><%= message %></li>
      <%end%>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="show">
  <%= form_with(model: @status, local:true) do |f| %>
  <div class="card-header fw-bold">
    <div class="col-4">
      <div class="form" style="color: black;">
        <%= f.label :date, class:"form-label text-center", placeholder:"Choose date" %>
          <%= f.date_field :date, class: "form-control", id: 'date' %>
        <%= f.label :status_picture, class:"form-label text-center", placeholder:"Choose file" %>
          <%= f.file_field :status_picture, class: "form-control" %>
      </div>
    </div>
  </div>
  <h3 class="text-center mt-1">Status details</h3>
    <%= f.fields_for :tasks do |t| %>
      <%= render 'task_fields' , :f=> t %>
    <% end %>
  <div>
    <br />
      <%= link_to_add_association f, :tasks do %>
        <button class="btn btn-primary" type="submit">Add task</button>
      <% end %>
  </div>
  <div class="row">
    <div class="col-4">
      <div class="form-group text-center mt-4 ms-1">
        <div class="actions">
          <%= f.submit(@status.new_record? ? "Save & Send email" : "Update status" ,class: "btn btn-primary")%>
        </div>
        </div>
      </div>
      <div class="col-4 mt-4" style="margin-left: -70px;">
        <% link_to @status, id: "preview", remote: true %>
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Preview
          </button>
        <% end %>
      </div>
    </div>
</div>

app/views/statuses/_messages.html.erb
<div class="container mt-1 mb-1">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close text-right" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>  
  <% end %>
</div>

app/views/statuses/_show.html.erb
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="container">
                <div class="card text-center">
                    <div class="card-header">
                      <h4>Date : <%= @status.date.strftime("%d/%m/%Y") %></h4>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Task name</th>
                                <th scope="col">Git PR</th>
                                <th scope="col">Hour</th>
                              </tr>
                            </thead>
                            <tbody>
                            <% @tasks.each.with_index(1) do |task,index| %>
                              <tr>
                                <th scope="row"><%= index %></th>
                                <td><%= task.task_name %></td>
                                <td><%= link_to "Github PR", task.git_pr_link, target: '_blank' %></td>
                                <td><%= task.hour %></td>
                              </tr>
                              <% end %>
                            </tbody>
                          </table>
                    </div>
                </div>
            </div> 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Understood</button>
        </div>
      </div>
    </div>
  </div>

app/views/statuses/_task_fields.html.erb
<div class="nested-fields">
    <div class="row mt-4 mb-4">
        <div class="col-6 ms-4">
            <div class="form-outline">
                <%= f.label :task_name,"Task name", class: "form-label" %>
                <%= f.text_field :task_name, class: "form-control" %>
            </div>
        </div>
        <div class="col-4">
            <div class="form-outline">
                <%= f.label :git_pr_link, "Git Pr", class: "form-label" %>
                <%= f.url_field :git_pr_link, type: "url", class: "form-control" %>
            </div>
        </div>
        <div class="col me-4">
            <div class="form-outline">
                <%= f.label :hour,class: "form-label" %>
                <%= f.text_field :hour, type: "number", class: "form-control" %>
            </div>
        </div>
    </div>
    <%= link_to_remove_association "Delete", f %>
 </div>

app/views/statuses/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
  <div class="container-fluid text-center">
    <div class="container px-5 my-5">
      Welcome to the Dashboard...
    </div>
  </div>
</body>
<%= render 'layouts/footer'%>
</html>

app/views/statuses/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
   <div class="container-fluid text-center">
     <div class="container px-5 my-5">
            <div class="display-6 text-center mt-1">Edit status</div>
            <div class="card mt-2 shadow">
                <%= render 'form'%>
         </div>
   </div>
   <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </div>
</body>
<%= render 'layouts/footer'%>
</html>

app/views/statuses/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>statuses</title>
</head>
<body>
    <h1 class="text-center mt-2">Statuses</h1>
    <div class="col-xl-3 col-lg-6 text-center ms-3 mb-2">
      <div class="card l-bg-blue-dark">
          <div class="card-statistic-3 p-4">
              <div class="card-icon card-icon-large"><i class="fa fa-list"></i></div>
                 <div class="mb-4">
                    <h5 class="card-title mb-0">Total Status</h5>
                  </div>
                  <div class="row align-items-center mb-2 d-flex">
                    <div class="col-8">
                       <h3 class="d-flex align-items-center mb-0">
                          <%= pluralize(@statuses.count, "status") %>
                       </h3>
                    </div>
                </div>
            </div>
       </div>
   </div>  
    <div class="flickr_pagination">
      <%= will_paginate @statuses, :container => false %>
    </div>
    <% @statuses.each do |status| %>
      <% if status.tasks.any? %>
    <div class="card-body">
       <div class="card-header text-center fw-bold">
          Date: <%= status.date.strftime("%d/%m/%Y") %>
       </div>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Task name</th>
                <th scope="col">Git PR</th>
                <th scope="col">Hour</th>
              </tr>
            </thead>
            <tbody>
                <% status.tasks.each.with_index(1) do |task,index| %>
                    <tr>
                      <th scope="row"><%= index %></th>
                      <td><%= task.task_name %></td>
                      <td><%= link_to "Github PR", task.git_pr_link, target: '_blank' %></td>
                      <td><%= task.hour %></td>
                    </tr>
                <% end %>
            </tbody>
          </table>
    </div>
    <div class="card-footer text-center fw-bold ms-3 me-3">
       Total hour(s) : <%= pluralize(status.total_hours_count, "hour")%>
       <div class="text-center">
         <%= link_to "Edit", edit_status_path(status),class:"me-2"%>
         <%= link_to "Delete", status_path(status), method: :delete, data: { confirm: "Are you sure ?" }%>
       </div>
    </div>
<% end %>
<% end %>
<div class="flickr_pagination mt-3">
  <%= will_paginate @statuses, :container => false %>
</div>
</body>
<%= render 'layouts/footer'%>
</html>

app/views/statuses/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <div class="container-fluid text-center">
     <div class="container px-5 my-5">
            <div class="display-6 text-center mt-1">Create new status</div>
            <div class="card mt-2 shadow">
                <%= form_with(model: @status, local:true) do |f| %>
                    <div class="card-header fw-bold">
                        <div class="col-4">
                            <div class="form-outline">
                                <%= f.label :date, class:"form-label text-center", placeholder:"Choose date" %>
                                <%= f.date_field :date,class: "form-control" %>
                            </div>
                        </div>
                    </div>
                    <h3 class= "text-center mt-1">Status details</h3>
                        <%= f.fields_for :tasks do |t| %>
                          <%= render 'task_fields', :f => t %>
                      <% end %>
                      <div>
                          <br/>
                          <%= link_to_add_association f, :tasks do %>
                             <button class="btn btn-primary" type="submit">Add task</button>
                          <% end %>
                      </div>
                    <div class="form-group text-center mt-4" style="margin-right: 82%;">
                        <%= f.submit "Send email",class: "btn btn-primary"%>
                    </div>
                <% end %>
         </div>
   </div>
   <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </div>
  <%= render 'layouts/footer'%>
</body>
</html>

app/views/statuses/show.html.erb
<h1 class="text-center mt-2">Status details</h1>
<div class="col-md-10 ">
    <div class="row ">
        <div class="col-xl-3 col-lg-6 text-center ms-3 mb-2">
            <div class="card l-bg-blue-dark">
                <div class="card-statistic-3 p-4">
                    <div class="card-icon card-icon-large"><i class="fa fa-tasks"></i></div>
                       <div class="mb-4">
                          <h5 class="card-title mb-0">Total task</h5>
                        </div>
                        <div class="row align-items-center mb-2 d-flex">
                          <div class="col-8">
                             <h3 class="d-flex align-items-center mb-0">
                                <%= pluralize(@tasks.count, "task") %>
                             </h3>
                          </div>
                      </div>
                  </div>
             </div>
         </div>  
        <div class="col-xl-3 col-lg-6 text-center">
            <div class="card l-bg-blue-dark">
                <div class="card-statistic-3 p-4">
                    <div class="card-icon card-icon-large"><i class="fa fa-clock" aria-hidden="true" ></i></div>
                    <div class="mb-4">
                        <h5 class="card-title mb-0">Total hour</h5>
                    </div>
                    <div class="row">
                        <div class="col-10">
                            <h3>
                                <%= pluralize(@status.total_hours_count, "hour") %>
                            </h3>
                        </div>
                    </div>
                </div>
          </div>
      </div>  
  </div>
</div>
<div class="container">
    <div class="card text-center">
        <div class="card-header">
          <h4>Date : <%= @status.date.strftime("%d/%m/%Y") %></h4>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Task name</th>
                    <th scope="col">Git PR</th>
                    <th scope="col">Hour</th>
                  </tr>
                </thead>
                <tbody>
                <% @tasks.each.with_index(1) do |task,index| %>
                  <tr>
                    <th scope="row"><%= index %></th>
                    <td><%= task.task_name %></td>
                    <td><%= link_to "Github PR", task.git_pr_link, target: '_blank' %></td>
                    <td><%= task.hour %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
        </div>
    </div>
</div>
<%= render 'layouts/footer'%>

app/views/statuses/show.js.erb
$('.statuses-container').html("<%= j (render partial: 'show') %>")